In [1]:
chinese_zodiac = "猴鸡狗猪鼠牛虎兔龙蛇马羊"
year = 2019
print(year % 12)

3


In [2]:
print(chinese_zodiac[year % 12])

猪


In [4]:
print('猪' in chinese_zodiac)

True


In [3]:
zodiac = ('摩羯座', '水瓶座', '双鱼座', '白羊座', '金牛座', '双子座', 
          '巨蟹座', '狮子座', '处女座', '天秤座', '天蝎座', '射手座')
zodiac_days = ((1, 20), (2, 19), (3, 21), (4, 21), (5, 21), (6, 22), 
               (7, 23), (8, 23), (9, 23), (10, 23), (11, 23), (12, 23))
month, day = 9, 2
zodiac_day = filter(lambda x: x <= (month, day), zodiac_days)
print(zodiac[len(list(zodiac_day))])

处女座


In [20]:
a_list = ['abc', 'xyz']
a_list.append('edf')
print(a_list)
a_list.remove('xyz')
print(a_list)

['abc', 'xyz', 'edf']
['abc', 'edf']


In [21]:
year = int(input("请输入出生年份"))
if chinese_zodiac[year % 12] == "猪":
    print("猪年大吉")

请输入出生年份2019
猪年大吉


In [22]:
for cz in chinese_zodiac:
    print(cz)

猴
鸡
狗
猪
鼠
牛
虎
兔
龙
蛇
马
羊


In [25]:
for i in range(1, 13):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [27]:
num = 1
while True:
    print(num)
    if num >= 10:
        break
    num += 1

1
2
3
4
5
6
7
8
9
10


In [36]:
month, day = (int(i) for i in input('请输入月日，使用空格分离:').strip().split())
for zd in range(len(zodiac_days)):
    if (month, day) <= zodiac_days[zd]:
        print(zodiac[zd])
        break
    elif month == 12 and day > 23:
        print(zodiac[0])
        break

请输入月日，使用空格分离:12 24
摩羯座


In [6]:
month, day = (int(i) for i in input('请输入月日，使用空格分离:').strip().split())
n = 0
while (month, day) > zodiac_days[n]:
    print(n)
    if month == 12 and day > 23:
        break
    n += 1
print(zodiac[n])

请输入月日，使用空格分离:1 13
摩羯座


In [7]:
dict1 = {}
type(dict1)

dict

In [12]:
dict2 = {}
type(dict2)

dict

In [10]:
set1 = set()
set1

set()

In [11]:
type(set1)

set

In [13]:
with open('test.txt', 'r') as f:
    print(f.read())

It's a test file.


In [25]:
with open('test.txt', 'w+') as f:
    f.write('rewrite file')
with open('test.txt', 'r') as f:
    print(f.readable())
    print(f.readline())
    # 已读完游标到文件尾部 所以什么也没有
    print(f.tell())
    print(f.readlines())
    # 将游标置于文件首部 再次读取
    f.seek(0)
    print(f.tell())
    print(f.readlines())

True
rewrite file
12
[]
0
['rewrite file']


In [26]:
try:
    1/0
except Exception as e:
    print(e)

division by zero


In [28]:
list1 = [1, 2, 3]
it = iter(list1)
it

In [29]:
next(it)

1

In [33]:
type(it)

list_iterator

In [43]:
def myrange(start, end, step):
    x = start
    while x < end:
        yield x
        x += step

In [44]:
type(myrange)

function

In [47]:
r = myrange(0, 1, 0.5)
type(r)

generator

In [45]:
for i in myrange(0, 10, 0.5):
    print(i)

0
0.5
1.0
1.5
2.0
2.5
3.0
3.5
4.0
4.5
5.0
5.5
6.0
6.5
7.0
7.5
8.0
8.5
9.0
9.5


In [50]:
r = range(10)
type(r)

range

In [51]:
with open('test.txt', 'r') as f:
    list_text = []
    for row in f:
        list_text.extend(row.strip().split())
print(list_text)

['rewrite', 'file', 'one', 'two']


In [52]:
lambda :True

<function __main__.<lambda>()>

In [56]:
func = lambda x, y: x + y
func

<function __main__.<lambda>(x, y)>

In [54]:
type(func)

function

In [55]:
func(1, 99)

100

In [57]:
a = [1, 2, 3, 4, 5]
list(filter(lambda x: x > 2, a))

[3, 4, 5]

In [58]:
list(map(lambda x: x + 10, a))

[11, 12, 13, 14, 15]

In [59]:
from functools import reduce
reduce(lambda x, y: x + y, a)

15

In [61]:
list(zip((1,2,3), (4,5,6)))

[(1, 4), (2, 5), (3, 6)]

In [62]:
d = {1:'haha', 2:'hehe'}
d

{1: 'haha', 2: 'hehe'}

In [63]:
dict(zip(d.values(), d.keys()))

{'haha': 1, 'hehe': 2}

In [67]:
def counter():
    cnt = [0]
    def add_one():
        cnt[0] += 1
        return cnt[0]
    return add_one

num1 = counter()
print(num1())
print(num1())
print(num1())
print(num1())
print(num1())

1
2
3
4
5


In [68]:
def a_line(a, b):
    def arg_y(x):
        return a * x + b
    return arg_y

line1 = a_line(3, 5)
line1(10)

35

In [70]:
line1(20)

65

In [71]:
# 装饰器
import time
def timer(func):
    def wrapper():
        start = time.time()
        func()
        end = time.time()
        print('运行时间：{}秒'.format(end-start))
    return wrapper

@timer
def i_can_sleep():
    time.sleep(3)
    
i_can_sleep()

运行时间：3.0003292560577393秒


In [72]:
def tips(func):
    def wrapper(a, b):
        print('start')
        func(a, b)
        print('end')
    return wrapper

@tips
def add(a, b):
    print(a + b)
    
add(1, 2)

start
3
end


In [78]:
def new_tips(argv):
    def tips(func):
        def wrapper(a, b):
            print('start {} {}'.format(func.__name__, argv))
            func(a, b)
            print('end')
        return wrapper
    return tips

@new_tips('add_module')
def add(a, b):
    print(a + b)
    
    
@new_tips('sub_module')
def sub(a, b):
    print(a - b)
    
add(1, 2)
sub(3, 1)

start add add_module
3
end
start sub sub_module
2
end


In [79]:
a = add(100, 1)
a

start add add_module
101
end


In [81]:
add.__name__

'wrapper'

In [84]:
from functools import wraps

def new_tips(argv):
    def tips(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            print('start {} {}'.format(func.__name__, argv))
            func(*args, **kwargs)
            print('end')
        return wrapper
    return tips

@new_tips('add_module')
def add(a, b):
    print(a + b)

In [85]:
add.__name__

'add'

In [4]:
class Player:
    '''玩家类'''
    def __init__(self, name, hp, occu):
        self.__name = name
        self.hp = hp
        self.occu = occu
        
    def print_player_info(self):
        print('{}:{}'.format(self.__name, self.hp))
        
    def update_name(self, name):
        self.__name = name
        
tom = Player('tom', 100, 'war')
jerry = Player('jerry', 999, 'monster')

tom.print_player_info()
jerry.print_player_info()

tom.update_name('R.M.B')
tom.print_player_info()

tom:100
jerry:999
R.M.B:100


In [33]:
class Monster:
    '''怪物类'''
    def __init__(self, hp):
        self.hp = hp
        
    def run(self):
        print('移动到某个位置')
        
    def whoami(self):
        print('我是怪物')


class Animals(Monster):
    '''普通怪物'''
    pass
#     def __init__(self, hp=10):
#         super().__init__(hp)
    
    
class Boss(Monster):
    '''Boss'''
    def whoami(self):
        print('我是Boss 我怕谁')

In [34]:
a1 = Monster(200)
print(a1.hp)
a1.run()

200
移动到某个位置


In [35]:
a2 = Animals(1)
print(a2.hp)
a2.run()

1
移动到某个位置


In [36]:
a3 = Boss(8888)
a3.whoami()

我是Boss 我怕谁


In [37]:
isinstance(a3, Monster)

True

In [38]:
isinstance(a2, Animals)

True

In [39]:
isinstance(a1, Monster)

True

In [40]:
isinstance(a1, Animals)

False

In [51]:
# 自定义with语句
class Testwith():
    def __enter__(self):
        print('run')
        
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_tb is None:
            print('no error')
        else:
            print('has error %s'% exc_tb)
        
with Testwith():
    print('Test is running')

run
Test is running
no error


In [52]:
with Testwith():
    print('Test is running')
    raise NameError('testNameError')

run
Test is running
has error <traceback object at 0x10e58aa08>


NameError: testNameError

In [70]:
import threading

# 多线程
def my_thread(arg1, arg2):
    print(threading.current_thread().getName(), 'start!')
    print('%s, %s' % (arg1, arg2))
    
for i in range(1, 6):
    t1 = threading.Thread(target=my_thread, args=(i, i+1))
    t1.start()
    
print(threading.current_thread().getName(), 'end')

Thread-80 Thread-81start!
Thread-82 1, 2
start!Thread-83
2, 3Thread-84MainThread  start!
4, 5

 start!
3, 4
 start!
5, 6
end


In [75]:
for i in range(1, 6):
    t1 = threading.Thread(target=my_thread, args=(i, i+1))
    t1.start()
    # MainThread最后执行
    t1.join()
    
print(threading.current_thread().getName(), 'end')

Thread-101 start!
1, 2
Thread-102 start!
2, 3
Thread-103 start!
3, 4
Thread-104 start!
4, 5
Thread-105 start!
5, 6
MainThread end


In [74]:
class MyThread(threading.Thread):
    def run(self):
        print(threading.current_thread().getName(), 'start')
        print('run')
        print(threading.current_thread().getName(), 'end')


t1 = MyThread()
t1.start()

Thread-100 start
run
Thread-100 end


In [77]:
import queue

q = queue.Queue()
q.put(1)
q.put(2)
q.put(3)
q.get()

1

In [78]:
q.get()

2

In [1]:
# 生产者与消费者
from threading import Thread, current_thread
from queue import Queue
import random
import time

queue = Queue(5)

class ProducterThread(Thread):
    '''生产者'''
    def run(self):
        name = current_thread().getName()
        nums = range(100)
        global queue
        while True:
            num = random.choice(nums)
            queue.put(num)
            print('生产者{} 生产了数据{}'.format(name, num))
            t = random.randint(1, 3)
            time.sleep(t)
            print('生产者{} 睡眠了{} 秒'.format(name, t))
            
            
class CustomerThread(Thread):
    '''消费者'''
    def run(self):
        name = current_thread().getName()
        global queue
        while True:
            num = queue.get()
            queue.task_done()
            print('消费者{} 消费了数据{}'.format(name, num))
            t = random.randint(1, 5)
            time.sleep(t)
            print('消费者{} 睡眠了{} 秒'.format(name, t))
        

In [2]:
producter = ProducterThread()
producter.start()
customer = CustomerThread()
customer.start()

生产者Thread-4 生产了数据17
消费者Thread-5 消费了数据17
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据62
消费者Thread-5 睡眠了4 秒
消费者Thread-5 消费了数据62
生产者Thread-4 睡眠了2 秒
生产者Thread-4 生产了数据4
生产者Thread-4 睡眠了1 秒
生产者Thread-4 生产了数据74
消费者Thread-5 睡眠了5 秒
消费者Thread-5 消费了数据4
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据45
消费者Thread-5 睡眠了1 秒
消费者Thread-5 消费了数据74
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据39
消费者Thread-5 睡眠了2 秒
消费者Thread-5 消费了数据45
生产者Thread-4 睡眠了2 秒
生产者Thread-4 生产了数据14
消费者Thread-5 睡眠了4 秒
消费者Thread-5 消费了数据39
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据0
消费者Thread-5 睡眠了2 秒生产者Thread-4 睡眠了1 秒
生产者Thread-4 生产了数据55

消费者Thread-5 消费了数据14
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据81
生产者Thread-4 睡眠了1 秒
生产者Thread-4 生产了数据80
消费者Thread-5 睡眠了5 秒
消费者Thread-5 消费了数据0
生产者Thread-4 睡眠了2 秒
生产者Thread-4 生产了数据58
消费者Thread-5 睡眠了2 秒
消费者Thread-5 消费了数据55
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据53
消费者Thread-5 睡眠了4 秒
消费者Thread-5 消费了数据81
消费者Thread-5 睡眠了1 秒
消费者Thread-5 消费了数据80
生产者Thread-4 睡眠了3 秒
生产者Thread-4 生产了数据23
消费者Thread-5 睡眠了2 秒
消费者Thread-5 消费了数据58
生产者Thread-4 睡眠了3 秒
生产者Thread

In [1]:
# python标准库
# re
import re
s = '2018-08-08'
regex = re.compile(r'(\d+)-(\d+)-(\d+)')
# match从头匹配
res = regex.match(s)
res

<_sre.SRE_Match object; span=(0, 10), match='2018-08-08'>

In [2]:
res.group()

'2018-08-08'

In [3]:
res.groups()

('2018', '08', '08')

In [5]:
type(res.groups())

tuple

In [6]:
year, month, day = res.groups()
print(year, month, day)

2018 08 08


In [7]:
res.group(1)

'2018'

In [8]:
type(res.group(1))

str

In [13]:
# search搜索
s = 'aaa2018-08-08bbb'
res = regex.search(s)
res

<_sre.SRE_Match object; span=(3, 13), match='2018-08-08'>

In [14]:
res.groups()

('2018', '08', '08')

In [16]:
# sub替换字符串
res = regex.sub('我是替换后的字符串', s)
res

'aaa我是替换后的字符串bbb'

In [17]:
# 时间
import time
print(time.time())

1567736509.184439


In [18]:
time.localtime()

time.struct_time(tm_year=2019, tm_mon=9, tm_mday=6, tm_hour=10, tm_min=21, tm_sec=56, tm_wday=4, tm_yday=249, tm_isdst=0)

In [25]:
time.strftime('%Y-%m-%d %H:%M:%S')

'2019-09-06 10:24:56'

In [24]:
time.strptime('2008-08-08 12:13:14', '%Y-%m-%d %H:%M:%S')

time.struct_time(tm_year=2008, tm_mon=8, tm_mday=8, tm_hour=12, tm_min=13, tm_sec=14, tm_wday=4, tm_yday=221, tm_isdst=-1)

In [23]:
time.strptime?

In [26]:
# datetime一般用作时间加减计算
import datetime
datetime.datetime.now()

datetime.datetime(2019, 9, 6, 10, 25, 29, 638673)

In [30]:
# 计算10分钟后的时间
print('当前时间：', datetime.datetime.now())
new_time = datetime.timedelta(minutes=10)
print('10分钟后的时间：', datetime.datetime.now() + new_time)

当前时间： 2019-09-06 10:28:01.182719
10分钟后的时间： 2019-09-06 10:38:01.182977


In [32]:
# random随机数
import random
for i in range(10):
    print(random.randint(1, 5))

2
4
1
5
5
4
1
3
4
3


In [34]:
# 文件操作
import os
os.path.abspath('.')

'/Users/dk/Desktop/Git/Reading-notes/极客时间'

In [35]:
os.path.exists('/Users')

True

In [37]:
os.path.isdir('/Users')

True

In [38]:
os.path.join('/Users', 'a/b/c')

'/Users/a/b/c'

In [49]:
os.listdir('/tmp')

['.keystone_install_lock',
 'com.apple.launchd.3xGV7uEmSi',
 'powerlog',
 'com.apple.launchd.62Qy9cdUIc',
 'android-dk',
 'nemu-gles-vpipe',
 'com.sogou.inputmethod',
 'mongodb-27017.sock',
 '.nemu-dk-ipc',
 'nemu-audio-vpipe']

In [43]:
from pathlib import Path
p = Path('.')
p.resolve()

PosixPath('/Users/dk/Desktop/Git/Reading-notes/极客时间')

In [45]:
p.is_dir()

True

In [51]:
p1 = Path('/tmp/a/b/c')
Path.mkdir(p1, parents=True)

In [52]:
os.listdir('/tmp')

['.keystone_install_lock',
 'com.apple.launchd.3xGV7uEmSi',
 'powerlog',
 'com.apple.launchd.62Qy9cdUIc',
 'android-dk',
 'nemu-gles-vpipe',
 'a',
 'com.sogou.inputmethod',
 'mongodb-27017.sock',
 '.nemu-dk-ipc',
 'nemu-audio-vpipe']

In [54]:
# numpy 用于高性能科学计算和数据分析，是常用的高级数据分析库的基础包
import numpy as np

arr1 = np.array([1, 2, 4])
arr1

array([1, 2, 4])

In [55]:
arr1.dtype

dtype('int64')

In [56]:
arr2 = np.array([1.3, 3.1, 4.3])
arr2.dtype

dtype('float64')

In [57]:
arr1 + arr2

array([2.3, 5.1, 8.3])

In [58]:
arr2 * 10

array([13., 31., 43.])

In [62]:
data = [[1, 2, 3], [4, 5, 6.6]]
data

[[1, 2, 3], [4, 5, 6.6]]

In [63]:
arr3 = np.array(data)
arr3

array([[1. , 2. , 3. ],
       [4. , 5. , 6.6]])

In [64]:
arr3.dtype

dtype('float64')

In [66]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
np.zeros((10,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
# 随机值
np.empty((2,2))

array([[4.51774098e-037, 6.82465630e-067],
       [1.27958000e+165, 1.10952331e-047]])

In [73]:
arr4 = np.arange(10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr4[4:5]

array([4])

In [76]:
type(arr4[4:5])

numpy.ndarray

In [78]:
arr4[4]

4

In [84]:
arr_slice = arr4[5:8]
arr_slice

array([5, 6, 7])

In [85]:
arr_slice[0] = 99

In [86]:
arr4

array([ 0,  1,  2,  3,  4, 99,  6,  7,  8,  9])

In [88]:
# pandas
import pandas as pd

obj = pd.Series([4, 5, 6, -7])
obj

0    4
1    5
2    6
3   -7
dtype: int64

In [92]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [90]:
obj.values

array([ 4,  5,  6, -7])

In [94]:
obj2 = pd.Series([3, 4, 7, 6], index=['f', 'g', 7, 'hh'])
obj2

f     3
g     4
7     7
hh    6
dtype: int64

In [95]:
obj2[7]

7

In [97]:
obj2['f']

3

In [98]:
obj2['a']

KeyError: 'a'

In [99]:
sdata = {'bj': 55000, 'sh': 6600, 'gz':77000, 'sz':99441}
obj3 = pd.Series(sdata)
obj3

bj    55000
sh     6600
gz    77000
sz    99441
dtype: int64

In [102]:
data = {'city': ['sh', 'sz', 'gz', 'bj'],
       'year': [17, 18, 19, 19],
       'pop': [1, 2, 1, 2]}
frame = pd.DataFrame(data)
frame

city  year  pop
0   sh    17    1
1   sz    18    2
2   gz    19    1
3   bj    19    2

In [105]:
# 排序
frame2 = pd.DataFrame(data, columns=['year', 'city', 'pop'])
frame2

year city  pop
0    17   sh    1
1    18   sz    2
2    19   gz    1
3    19   bj    2

In [106]:
frame2['new'] = 100
frame2

year city  pop  new
0    17   sh    1  100
1    18   sz    2  100
2    19   gz    1  100
3    19   bj    2  100

In [107]:
frame2['old'] = [1, 2, 3, 5]
frame2

year city  pop  new  old
0    17   sh    1  100    1
1    18   sz    2  100    2
2    19   gz    1  100    3
3    19   bj    2  100    5

In [108]:
frame2['cap'] = frame2.city == 'bj'
frame2

year city  pop  new  old    cap
0    17   sh    1  100    1  False
1    18   sz    2  100    2  False
2    19   gz    1  100    3  False
3    19   bj    2  100    5   True

In [109]:
# 转置
frame2.T

0      1      2     3
year     17     18     19    19
city     sh     sz     gz    bj
pop       1      2      1     2
new     100    100    100   100
old       1      2      3     5
cap   False  False  False  True

In [110]:
obj4 = pd.Series([4.3, 2.3, 1, 5], index=['a', 'x', 'd', 'df'])
obj4

a     4.3
x     2.3
d     1.0
df    5.0
dtype: float64

In [111]:
obj5 = obj4.reindex([1, 3, 5, 7])
obj5

1   NaN
3   NaN
5   NaN
7   NaN
dtype: float64

In [112]:
obj6 = obj4.reindex([1, 3, 5, 7], fill_value=0)
obj6

1    0.0
3    0.0
5    0.0
7    0.0
dtype: float64

In [113]:
obj7 = obj4.reindex(['x', 'a', 'd', 'df'])
obj7

x     2.3
a     4.3
d     1.0
df    5.0
dtype: float64

In [114]:
obj8 = pd.Series(['blue', 'purple', 'yellow'], index=(0, 2, 4))
obj8

0      blue
2    purple
4    yellow
dtype: object

In [115]:
obj8.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [117]:
# 使用下面的值补充缺失值
obj8.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [118]:
from numpy import nan as NA

data = pd.Series([1, NA, 3])
data

0    1.0
1    NaN
2    3.0
dtype: float64

In [119]:
# 删除缺失值
data.dropna()

0    1.0
2    3.0
dtype: float64

In [120]:
data2 = pd.DataFrame([[1, 6.5, 3], [1, NA, NA], [NA, NA, NA]])
data2

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN

In [121]:
data2.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN

In [122]:
data2

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN

In [123]:
data2.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN

In [124]:
# 填充缺失值
data2.fillna(0)

0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0

In [125]:
data2

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN

In [126]:
data2.fillna(0, inplace=True)

In [127]:
data2

0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0

In [128]:
# 层次化索引
data3 = pd.Series(np.random.randn(10),
                 index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data3

a  1   -1.194710
   2   -0.609115
   3    1.052927
b  1   -0.288856
   2   -0.543601
   3    0.487043
c  1   -0.270111
   2   -0.929719
d  2    0.263725
   3   -1.007620
dtype: float64

In [129]:
data3['b']

1   -0.288856
2   -0.543601
3    0.487043
dtype: float64

In [130]:
data3['b':'c']

b  1   -0.288856
   2   -0.543601
   3    0.487043
c  1   -0.270111
   2   -0.929719
dtype: float64

In [131]:
data3.unstack()

1         2         3
a -1.194710 -0.609115  1.052927
b -0.288856 -0.543601  0.487043
c -0.270111 -0.929719       NaN
d       NaN  0.263725 -1.007620

In [132]:
data3.unstack().stack()

a  1   -1.194710
   2   -0.609115
   3    1.052927
b  1   -0.288856
   2   -0.543601
   3    0.487043
c  1   -0.270111
   2   -0.929719
d  2    0.263725
   3   -1.007620
dtype: float64